name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Show workspace (debug)
        run: |
          pwd
          ls -R

      - name: Restore
        run: dotnet restore ModernSoftwareApp.sln

      - name: Build (Release)
        run: dotnet build ModernSoftwareApp.sln --no-restore --configuration Release

      - name: Test (unit)
        run: dotnet test ModernSoftwareApp.Tests/ModernSoftwareApp.Tests.csproj --no-build --configuration Release --verbosity normal

      - name: Check formatting (non-blocking)
        run: dotnet format ModernSoftwareApp.sln --verify-no-changes --verbosity diagnostic
        continue-on-error: true
